### ISSUE TITLE
React warnings on styleguide

### ISSUE THREAD

**Issue by alexandre-lelain** [attineos/atti-components#101]
Hello,

There are too many React warnings thrown at styleguide start:

- "Warning: `value` prop on `select` should not be null"
- `Select` component is switching between controlled and uncontrolled mode which is not advised by React
- "Warning: Failed prop type: Invalid prop `variance` of value `normal` supplied to `Button`, expected one of ["primary","neutral","light","dark"]."
- "Warning: Failed prop type: Invalid prop `variance` of value `neutral` supplied to `InputFile`, expected one of ["primary","secondary","normal"]"
- `TableFacade`should render children with keys

Please fix those warnings in the stories of these components to limit the noise in the console.

**Comment by akaala** [comment]
@alexandre-lelain Can you please provide an updated list of warnings ?
Or even better, can you please try to fix them ? ^_^
