### ISSUE TITLE
Update repository/bugs/homepage sections of package.json

### ISSUE THREAD

**Issue by callain** [attineos/atti-components#110]
I believe this is what `npmjs` use to display information on the package page. https://www.npmjs.com/package/atti-components
I propose to use the netlify documentation url for the homepage until we make a new one.

```json
{
...
  "repository": "github:attineos/atti-components",
  "bugs": {
      "url": "https://github.com/attineos/atti-components/issues"
  },
  "homepage": "https://atti-components.netlify.com"
...
}

**Comment by akaala** [comment]
Merged
