### ISSUE TITLE
Create a new documentation

### ISSUE THREAD

**Issue by akaala** [attineos/atti-components#114]
Currently, the documentation using styleguidist isn't satisfying / not customizable enough, etc.

The idea is to create a new documentation using a stack based on [gatsby](https://www.gatsbyjs.org/) [mdx](https://mdxjs.com/) and [react-live](https://github.com/FormidableLabs/react-live).
This really [good article](https://medium.com/styled-components/how-to-build-a-great-component-library-a40d974a412d) explains some reasons for having a really good documentation and how they've implemented it.

Before creating the new documentation, we'll need #113 to be done.

**Comment by VictorGosse** [comment]
WIP in #153

**Comment by VictorGosse** [comment]
Released
