### ISSUE TITLE
Question: would these components work with preact?

### ISSUE THREAD

**Issue by proddy** [attineos/atti-components#152]
First of all thanks for providing and publicly sharing a comprehensive library. I was wondering whether I could use these components for a new project I'm working on? Thing is the pages need to be served from a web server running on an microcontroller (ESP8266) like @atrakeur did with his excellent [esp-domotic](https://github.com/atrakeur/esp-domotic). I choose Preact because of its minimal memory footprint. My current web code is based on plain JS with Bootstrap3 and its almost 500KB.

**Comment by atrakeur** [comment]
Preact support would be a really nice addition to this library. Preact is already compatible with all dependencies so it might be straight forward to implement it. However we had no time to look into it recently.

Maybe you can try to use the preact-compat package to ensure everything works: https://github.com/developit/preact-compat . As of now I see no reason for it to not work but yeah, havn't tested so who know?

Please report back once you managed to do it, and if you encontered any problems. I'll happily add instructions to the readme and fix any problem you may encounter.

**Comment by proddy** [comment]
sure, I'll give it a try and report back any findings here. thanks.
