### ISSUE TITLE
Compo proposal: (Data)Table

### ISSUE THREAD

**Issue by atrakeur** [attineos/atti-components#37]
We need a datatable composent for all our data display need. That compo must do the barebones of any table on any website, but also be extensible enough for any use.

The proposed interface for basic usage:
```jsx
<Table
    cols={[
        { name: "Item", key: "item" },
        { name: "Price", key: "price" },
    ]}
    data={[
        { id: 10, item: "Product 1", Price: 100 },
        { id: 12, item: "Product 5", Price: 50 },            
    ]}
/>
```

The idea is also to provide props for super charging parts of the rendering.
Props like `tableRenderer`, `headerRenderer`, `headerCellRenderer`, `lineRenderer` and `cellRenderer` may cover most of the cases.

As in Menu and Breadcrumb, supporting renderers in data objects is a must.

Then we will implement Datatable, a component that takes a (customisable!) Table and give us filtering, pagination, multiselect, etc etc

**Comment by Valulz** [comment]
Can you provide some examples of design/component of the datatable 🙏 ?

**Comment by Valulz** [comment]
For the props:

```js
{
  columns,
  data,
  tableRenderer,
  headerRenderer,
  headerCellRenderer,
  rowRenderer,
  rowCellRenderer,
  footerRenderer,
  footerCellRenderer,
}
```

Something like that ? Not a fan of line :p row is, I think, a bit more explicit ^^
