### ISSUE TITLE
Create a cellItem helper

### ISSUE THREAD

**Issue by VictorGosse** [attineos/atti-components#4]
Hey,

currently, when we are using the `Grid` component, we are forced to wrap all our subcomponents by the `Cell` component which adds some extra DOM.

Can you please create a new helper (called `cellItem` to avoid any conflict with `Cell` component for example) that will transform a component into a Cell and will use the `cols` props ?

Thanks

**Comment by atrakeur** [comment]
How do you imagine that as a final user?
Is it just a simple wrapper that create a Cell? Is it meant to be an annotation? 

What's the desired purpose of this? Reduce code size or improve readability? Auto populate cols values?

**Comment by akaala** [comment]
Done in #45
