### ISSUE TITLE
Button Loading State

### ISSUE THREAD

**Issue by Valulz** [attineos/atti-components#43]
Add a loading state on the button

**Comment by atrakeur** [comment]
Can be implemented by putting a <Loader /> as text of the button
Example:
```js
<Button>{isLoading ? <Loader />: "Click Me"}</Button>
```

AWe dont need anymere than that, but it's a good case for an example in the docs.

**Comment by atrakeur** [comment]
Closing as current API is flexible enought to let the caller handle that.
