### ISSUE TITLE
Create a Container Component

### ISSUE THREAD

**Issue by alexandre-lelain** [attineos/atti-components#54]
Heya,

It could be useful in some use-cases to have a styled-container-component. The idea would be to implement display, margins, paddings and sizes styled helpers, and add those to the container so we can use props to select the display of our choice for the container.

By default the container would be a div - but can be overrided with the `a` prop.

**Comment by atrakeur** [comment]
can be implemented as part of the https://atti-components.netlify.com/#/Layout?id=container ?
Or we will need another name!

**Comment by akaala** [comment]
Hello ! :)

Definitely, it shouldn't be part of the `Container` component as this compo has custom width and a totally different purpose ;).

Regarding this `Div` component (I think we can call it like this ;)) I see only 1 positive point:
- it saves time

But many negative points:
- runs unused code (it'll be really rare to use all the helpers it contains)
- don't promote the usage of semantic HTML. It'll be mainly used as a div without even thinking if it's the good HTML tag or not
- as soon as we'll need a functionnality not handled by this component, we'll need to create a new component...
- as soon as we'll need responsivness, it won't work without creating a new component (but this one is related the helpers)

This is only my POV and I also understand why you want it ;)

**Comment by akaala** [comment]
We discussed about it and we said that all the helpers exist and so if someone want to implement it on their website, it's really simple. Closing for now. 
We'll reopen if needed.
